### ISSUE TITLE
test fails during mvn install

### ISSUE THREAD

**Issue by kminooie** [chewiebug/GCViewer#116]
INFO:  [OC#39] Changing GC strategy from: singleparcon to: singleparpar, reason: Emergency parallel sweep requested.
dec 17, 2014 11:45:50 FM com.tagtraum.perf.gcviewer.imp.DataReaderJRockit1_6_0 read
INFO:  [OC#40] Changing GC strategy from: singleparpar to: singleparcon, reason: Return to basic strategy.
dec 17, 2014 11:45:50 FM com.tagtraum.perf.gcviewer.imp.DataReaderJRockit1_6_0 read
INFO:  [OC#41] Changing GC strategy from: singleparcon to: singleparpar, reason: Emergency parallel sweep requested.
dec 17, 2014 11:45:50 FM com.tagtraum.perf.gcviewer.imp.DataReaderJRockit1_6_0 read
INFO:  [OC#42] Changing GC strategy from: singleparpar to: singleparcon, reason: Return to basic strategy.
dec 17, 2014 11:45:50 FM com.tagtraum.perf.gcviewer.imp.DataReaderJRockit1_6_0 read
VARNING: GC log contains OutOfMemory error:  Throwing OutOfMemory: allocLargeObjectOrArray: [B, size 118101136
dec 17, 2014 11:45:50 FM com.tagtraum.perf.gcviewer.imp.DataReaderJRockit1_6_0 read
INFO: Reading done.
dec 17, 2014 11:45:50 FM com.tagtraum.perf.gcviewer.util.HttpUrlConnectionHelper openInputStream
INFO: Reading 559 bytes from http://localhost/gclog.txt; contentType = text/plain; contentEncoding = gzip; last modified = Wed Dec 17 11:38:46 PST 2014
dec 17, 2014 11:45:50 FM com.tagtraum.perf.gcviewer.util.HttpUrlConnectionHelper openInputStream
INFO: Reading 0 bytes from http://localhost/gclog.txt; contentType = text/html; charset=UTF-8; contentEncoding = gzip; last modified = -
dec 17, 2014 11:45:50 FM com.tagtraum.perf.gcviewer.util.HttpUrlConnectionHelper openInputStream
INFO: Server sent 404: Not found
dec 17, 2014 11:45:50 FM com.tagtraum.perf.gcviewer.util.HttpUrlConnectionHelper openInputStream
INFO: Reading 2944 bytes from http://localhost/gclog.txt; contentType = text/plain; contentEncoding = null; last modified = Wed Dec 17 11:38:46 PST 2014
dec 17, 2014 11:45:50 FM com.tagtraum.perf.gcviewer.util.HttpUrlConnectionHelper openInputStream
INFO: Reading 0 bytes from http://localhost/gclog.txt; contentType = text/html; charset=UTF-8; contentEncoding = null; last modified = -
dec 17, 2014 11:45:50 FM com.tagtraum.perf.gcviewer.util.HttpUrlConnectionHelper openInputStream
INFO: Server sent 404: Not found
Tests run: 233, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 9.711 sec <<< FAILURE!
openInputStreamGZipOk(com.tagtraum.perf.gcviewer.util.TestHttpUrlConnectionHelper)  Time elapsed: 0.157 sec  <<< FAILURE!
java.lang.AssertionError: openInputStream(conn,gzip): # bytes read at position 0 expected:<2944> but was:<2976>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at com.tagtraum.perf.gcviewer.util.TestHttpUrlConnectionHelper.verifyInputStreamWithFile(TestHttpUrlConnectionHelper.java:183)
	at com.tagtraum.perf.gcviewer.util.TestHttpUrlConnectionHelper.testOpenInputStreamOk(TestHttpUrlConnectionHelper.java:156)
	at com.tagtraum.perf.gcviewer.util.TestHttpUrlConnectionHelper.openInputStreamGZipOk(TestHttpUrlConnectionHelper.java:80)

Results :

Failed tests: 
  TestHttpUrlConnectionHelper.openInputStreamGZipOk:80->testOpenInputStreamOk:156->verifyInputStreamWithFile:183 openInputStream(conn,gzip): # bytes read at position 0 expected:<2944> but was:<2976>

Tests run: 233, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

**Comment by chewiebug** [comment]
Hmm, this seems to be quite tricky. In #120 someone has the same failure on a windows platform. Maybe, I'll have to rewrite this test to make it run on all platforms.

**Comment by chewiebug** [comment]
I have pushed a fix to the repository. Does the test failure now dissapear?

**Comment by cgrinds** [comment]
Yes, with your latest fix TestHttpUrlConnectionHelper passes.

**Comment by chewiebug** [comment]
Thanks a lot for checking!
