### ISSUE TITLE
feature request: Use native file dialog on OSX

### ISSUE THREAD

**Issue by cgrinds** [chewiebug/GCViewer#117]
JFileChooser is a bit of a pain on OSX. Keyboard shortcuts don't work well. For example, it's not possible to "Go to Folder" so you're forced to navigate via the UI. Being able to jump to a file anywhere on the filesystem by typing the path is a great feature of the native dialog.

**Comment by chewiebug** [comment]
Might be ok - I don't have a mac to test this. I'll merge it later.

**Comment by chewiebug** [comment]
Close this one, because it is fixed with pull request #123.
