### ISSUE TITLE
Brew installer for OS X

### ISSUE THREAD

**Issue by mrjcleaver** [chewiebug/GCViewer#122]
It would be nice if there was a brew installer or brew cask installer for GCViewer.

http://brew.sh

**Comment by chewiebug** [comment]
I have no mac to test it. If someone provides a pull request, I can merge it.

**Comment by fedragon** [comment]
I just opened a pull request on Homebrew (https://github.com/Homebrew/homebrew/pull/39441), let's see if they merge it :)

**Comment by mrjcleaver** [comment]
Thx! ;)

**Comment by jkaving** [comment]
This was actually merged (from [a different pull request](https://github.com/Homebrew/legacy-homebrew/pull/47778)) on Jan 19, 2016.
So GCViewer is available via Homebrew, and I guess this issue can be closed.

```
> brew info gcviewer
gcviewer: stable 1.34.1 (bottled)
Java garbage collection visualization tool
https://github.com/chewiebug/GCViewer
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gcviewer.rb
==> Dependencies
Build: maven ✘
==> Requirements
Required: java ✔
```

**Comment by mrjcleaver** [comment]
Great!
