### ISSUE TITLE
Javadocs cannot be built with Java 8

### ISSUE THREAD

**Issue by unguiculus** [chewiebug/GCViewer#124]
See http://blog.joda.org/2014/02/turning-off-doclint-in-jdk-8-javadoc.html for details.

**Comment by ecki** [comment]
@chewiebug can you comment on removing the date/tiemstamps from the javadocs? If you prefer to keep them I would maybe think a custom "@created" tag might be the way to go (there are different syntax). But I think this is task of git to keep track thats why I removed them from all touched comments (even if they do not triger doclint in some cases).

**Comment by chewiebug** [comment]
Hi Bernd,

I think, the creation information has mostly nostalgic value - some of 
the classes were created way before the were committed to github. But I 
don't think, they are a big loss, if we drop them.

Speaking of git keeping track of things: We might even throw out the 
"author" tags. Blaming is best done with git as well.

Best regards,
Jörg

**Comment by chewiebug** [comment]
I have merge #125, which fixes this issue.

@ecki Thanks again!
