### ISSUE TITLE
feature request : PNG file from current graph

### ISSUE THREAD

**Issue by YouriAndropov** [chewiebug/GCViewer#129]
Hi,

I would be nice if we could get a PNG of the current graph.
As you can open more than one gc log simultaneously, this feature should support that also.
We could keep the graph current height and width, or use particular values, eventually.

Thank you.

As a bonus, we could also be able to set the PNG height and width from the command line, and add or remove some metrics (permgen, young gen usage, old gen usage, ...)

**Comment by aolle** [comment]
Hi,

I forked the project. I'll implement this feature and I'll send a pull request. It's really nice when we need to get the graphs when we're making infraestructure reports at work.

Thank you.
Àngel Ollé Blázquez.

**Comment by chewiebug** [comment]
Hi Àngel,

Thank you very much for your contribution, I have merged #131.

I leave the issue open, because the "bonus" mentioned is not implemented (export chart with current settings).

Best regards,
Jörg

**Comment by chewiebug** [comment]
#227 adds exporting of the png file using the current settings -> closing this issue.
