### ISSUE TITLE
GCViewer does not work with G1

### ISSUE THREAD

**Issue by feng-tao** [chewiebug/GCViewer#133]
The JAVA_OPTS for my app is XX:+PrintGCDetails -verbose:gc -Xloggc:/tmp/gc.1 -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent . When I try to open the gc log with gcviewer, I encounter bunches of errors:

842:          [Processed Buffers: Min: 2, Avg: 2.5, Max: 3, Diff: 1, Sum: 10]
May 12, 2015 11:12:35 PM com.tagtraum.perf.gcviewer.imp.DataReaderSun1_6_0G1 read
WARNING: com.tagtraum.perf.gcviewer.imp.UnknownGcTypeException: Unknown gc type: 'Scan RS (ms)' Line 38843:       [Scan RS (ms): Min: 0.0, Avg: 0.0, Max: 0.0, Diff: 0.0, Sum: 0.0]
May 12, 2015 11:12:35 PM com.tagtraum.perf.gcviewer.imp.DataReaderSun1_6_0G1 read
WARNING: com.tagtraum.perf.gcviewer.imp.UnknownGcTypeException: Unknown gc type: 'Code Root Scanning (ms)' Line 38844:       [Code Root Scanning (ms): Min: 0.0, Avg: 0.0, Max: 0.0, Diff: 0.0, Sum: 0.0]
May 12, 2015 11:12:35 PM com.tagtraum.perf.gcviewer.imp.DataReaderSun1_6_0G1 read
WARNING: com.tagtraum.perf.gcviewer.imp.UnknownGcTypeException: Unknown gc type: 'Object Copy (ms)' Line 38845:       [Ob^CMay 12, 2015 11:12:35 PM com.tagtraum.perf.gcviewer.imp.DataReaderSun1_6_0G1 read
WARNING: com.tagtraum.perf.gcviewer.imp.UnknownGcTypeException: Unknown gc type: 'Termination (ms)' Line 38846:       [Termination (ms): Min: 0.0, Avg: 0.1, Max: 0.1, Diff: 0.1, Sum: 0.3]
May 12, 2015 11:12:35 PM com.tagtraum.perf.gcviewer.imp.DataReaderSun1_6_0G1 read
WARNING: com.tagtraum.perf.gcviewer.imp.UnknownGcTypeException: Unknown gc type: 'GC Worker Other (ms)' Line 38847:       [GC Worker Other (ms): Min: 0.0, Avg: 0.0, Max: 0.0, Diff: 0.0, Sum: 0.0]
May 12, 2015 11:12:35 PM com.tagtraum.perf.gcviewer.imp.DataReaderSun1_6_0G1 read
WARNING: com.tagtraum.perf.gcviewer.imp.UnknownGcTypeException: Unknown gc type: 'GC Worker Total (ms)' Line 38848:       [GC Worker Total (ms): Min: 0.6, Avg: 0.6, Max: 0.6, Diff: 0.1, Sum: 2.4]
May 12, 2015 11:12:35 PM com.tagtraum.perf.gcviewer.imp.DataReaderSun1_6_0G1 read
WARNING: com.tagtraum.perf.gcviewer.imp.UnknownGcTypeException: Unknown gc type: 'GC Worker End (ms)' Line 38849:       [GC Worker End (ms): Min: 19772.5, Avg: 19772.5, Max: 19772.5, Diff: 0.0]
May 12, 2015 11:12:35 PM com.tagtraum.perf.gcviewer.imp.DataReaderSun1_6_0G1 read
WARNING: com.tagtraum.perf.gcviewer.imp.UnknownGcTypeException: Unknown gc type: 'Code Root Fixup' Line 38850:    [Code Root Fixup: 0.0 ms]
May 12, 2015 11:12:35 PM com.tagtraum.perf.gcviewer.imp.DataReaderSun1_6_0G1 read
WARNING: com.tagtraum.perf.gcviewer.imp.UnknownGcTypeException: Unknown gc type: 'Code Root Purge' Line 38851:    [Code Root Purge: 0.0 ms]

**Comment by chewiebug** [comment]
Hi,

Could you please send me the first few lines of the warning window, 
where your GCViewer version is shown and send the logfile to 
gcviewer-info@googlegroups.com so that I can do some analysis?

Best regards,
Jörg

**Comment by chewiebug** [comment]
Hi,

Without more information I can't do anything here. Please reopen the issue, when you can provide more information.

Best regards,
Jörg

**Comment by follamor** [comment]
Hi chewiebug ,
  below the warning output including the first lines 

INFOS [DataReaderFacade]: GCViewer version 1.35-SNAPSHOT (2015-07-29T22:20:05+0200)
INFOS [DataReaderFactory]: File format: Sun 1.6.x G1 collector
INFOS [DataReaderSun1_6_0G1]: Reading Sun 1.6.x / 1.7.x G1 format...
INFOS [DataReaderSun1_6_0G1]: Java HotSpot(TM) 64-Bit Server VM (24.79-b02) for linux-amd64 JRE (1.7.0_79-b15), built on Apr 10 2015 11:34:48 by "java_re" with gcc 4.3.0 20080428 (Red Hat 4.3.0-8)
INFOS [DataReaderSun1_6_0G1]: Memory: 4k page, physical 32783264k(15189144k free), swap 15728636k(15606504k free)
INFOS [DataReaderSun1_6_0G1]: CommandLine flags: -XX:GCLogFileSize=52428800 -XX:InitialHeapSize=5368709120 -XX:MaxGCPauseMillis=4000 -XX:MaxHeapSize=5368709120 -XX:MaxPermSize=1610612736 -XX:NewRatio=3 -XX:NumberOfGCLogFiles=5 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+TieredCompilation -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseGCLogFileRotation 
AVERTISSEMENT [DataReaderSun1_6_0G1]: com.tagtraum.perf.gcviewer.imp.ParseException: java.lang.StringIndexOutOfBoundsException: String index out of range: 125 Line 13640: 2015-08-27T12:16:38.957+0100: 54609,326: [GC pause (young)2015-08-27T12:16:38.988+0100: 54609,357: [GC concurrent-mark-start]
AVERTISSEMENT [DataReaderSun1_6_0G1]: com.tagtraum.perf.gcviewer.imp.UnknownGcTypeException: Unknown gc type: '(to-space exhausted)' Line 13641:  (to-space exhausted), 0,7100870 secs]
AVERTISSEMENT [DataReaderSun1_6_0G1]: com.tagtraum.perf.gcviewer.imp.ParseException: java.lang.StringIndexOutOfBoundsException: String index out of range: 125 Line 14126: 2015-08-27T12:18:22.758+0100: 54713,127: [GC pause (young)2015-08-27T12:18:22.765+0100: 54713,134: [GC concurrent-mark-start]
AVERTISSEMENT [DataReaderSun1_6_0G1]: com.tagtraum.perf.gcviewer.imp.UnknownGcTypeException: Unknown gc type: '(to-space exhausted)' Line 14127:  (to-space exhausted), 0,8996920 secs]
AVERTISSEMENT [DataReaderSun1_6_0G1]: com.tagtraum.perf.gcviewer.imp.ParseException: java.lang.StringIndexOutOfBoundsException: String index out of range: 125 Line 14465: 2015-08-27T12:19:45.832+0100: 54796,201: [GC pause (young)2015-08-27T12:19:45.834+0100: 54796,203: [GC concurrent-mark-start]
AVERTISSEMENT [DataReaderSun1_6_0G1]: com.tagtraum.perf.gcviewer.imp.UnknownGcTypeException: Unknown gc type: '(to-space exhausted)' Line 14466:  (to-space exhausted), 0,6258080 secs]
INFOS [DataReaderSun1_6_0G1]: Done reading.


Regards,

**Comment by chewiebug** [comment]
Hi @follamor 

The problem I see here, is the concurrency of G1 that, unfortunately, makes its way into the log file mixing up lines. GCViewer can only cope with a fiew of those mixtures but failes with the rest - hence the warnings.

If you'd like a more detailed analysis of your log, please send a sample file to gcviewer-info@googlegroups.com referring to this issue (#133).
