### ISSUE TITLE
Some fullGC do not appear as such with CMS

### ISSUE THREAD

**Issue by acailley** [chewiebug/GCViewer#135]
Hi !

with CMS line
742285,854: [Full GC 742285,856: [CMS742292,433: [CMS-concurrent-mark: 9,640/12,329 secs] [Times: user=114,49 sys=1,09, real=12,33 secs] 
are not counted as a FullGC.

Then we only have a blank in the chart :

![capturefullgc](https://cloud.githubusercontent.com/assets/8916066/7772723/32313512-00a0-11e5-8c58-fb4fc8ae7c0f.jpg)

**Comment by acailley** [comment]
The complete file GC_IS_PRJ55310_150511_202134.7z is available at 
http://www.filedropper.com/gcisprj55310150511202134

**Comment by chewiebug** [comment]
Thanks for raising the issue and providing the log file. Usually gcviewer has no problems parsing a full gc mixed with a concurrent event. I'll have to check with the log file. 

I am on vacation until end of May, you'll have to be patient. 

Best regards, 
Jörg 


-------- Original Message --------

**Comment by chewiebug** [comment]
Sample log file can now be parsed without warnings, full gcs are recognised. The latest SNAPSHOT version of GCViewer contains the fix.

Thanks for raising this issue!

Best regards,
Jörg

**Comment by acailley** [comment]
Yes, looks like I did not have the last build/sources, a stupid mistake.
With the last build, I have no error and the fullGC are correctly displayed.

Thanks a lot for your work, sorry again for loosing your time.

**Comment by chewiebug** [comment]
Ah, well, no! I have indeed found a bug based on your issue description 
and published a fixed version. I just suspect, that you used an older 
version of the code for your analysis.

You didn't loose my time, you helped me improve GCViewer! Sorry for the 
confusion, I created!

Best regards,
Jörg
