### ISSUE TITLE
min / max interval for full gc

### ISSUE THREAD

**Issue by chewiebug** [chewiebug/GCViewer#14]
Assignee. @rollandf 

Another feature that could help with analysis is a "Min / max full GC pause interval", where we could see if Full GCs are happening too frequent, or not.

**Comment by rollandf** [comment]
@chewiebug hi,
I would like to look into this one.
Tell me if the description below answer this issue:
In the "Data Panel", "Pause" tab, "Full gc pauses" frame add a new line "Min / max full GC pause interval".
The value will be the maximum and minimum time between full GCs.

Thanks,
Fred

**Comment by chewiebug** [comment]
Hi Fred,

Yes, your description sums the requirement nicely up. Thank you for starting work on this one!

Best regards,
Jörg

**Comment by chewiebug** [comment]
Closing this issue, because it is solved with #166. Thank you, Fred!
