### ISSUE TITLE
have you seen lions-share?

### ISSUE THREAD

**Issue by fommil** [chewiebug/GCViewer#154]
I wrote a GC log analyser a few years ago:

  https://github.com/fommil/lions-share

it has a fair bit of testing around it too, but no G1.

**Comment by fommil** [comment]
specifically https://github.com/fommil/lions-share/blob/master/analysis/src/main/scala/com/github/fommil/lion/gc/parser.scala

**Comment by chewiebug** [comment]
Hi Sam

No, I didn't know your GC log analyser. It looks like your approach is a 
bit broader than just gc log analysis. And the parser looks nice and 
compact!

Are you hinting at something opening this issue?

Best regards,
Jörg

**Comment by fommil** [comment]
@chewiebug just wanted to bring it to your attention incase you want to avoid any wheel inventions! :-)

Since you're pure Java, you might just get some value from the tests.

**Comment by chewiebug** [comment]
Hi Sam,

Thank you very much! If you would like to contribute something to GCViewer, you are very welcome :smiley: (my time is currently very limited...). 

Best regards,
Jörg
