### ISSUE TITLE
Prevent closing of JCheckBoxMenuItem

### ISSUE THREAD

**Issue by henray** [chewiebug/GCViewer#173]
Hi, love this tool.

Would it be possible to implement a new feature so that when clicking any check boxes under View, the menu is not closed?

This would make it much smoother for some users. I have implemented the changes locally. Do you guys think this is a feature worth merging?

Thanks.

**Comment by chewiebug** [comment]
Yes, absolutely! Thank you very much for your pull request! I have merged it.

I have only used it for the "view" menu and removed all other references to the new MenuItem in the code.

**Comment by chewiebug** [comment]
SourceForge is currently mostly down. So the latest build including your new feature is not deployed there, yet. It will be, as soon as I see, that SourceForge is fully up and running again.

**Comment by henray** [comment]
Perfect. Thank you.

**Comment by chewiebug** [comment]
OK, now the build was successful again. You can download the latest 
binary from https://github.com/chewiebug/GCViewer/wiki/Changelog 
(1.35-SNAPSHOT).
