### ISSUE TITLE
UnifiedLogging from Java 11 not completely parsable

### ISSUE THREAD

**Issue by theobisproject** [chewiebug/GCViewer#204]
The information in the unified jvm logging is in Java 11 slightly different than in Java 9 and 10. Therefore parsing the gc logging from Java 11 fails with the following errors.

`WARNUNG [DataReaderUnifiedJvmLogging]: Failed to parse gc event (com.tagtraum.perf.gcviewer.imp.UnknownGcTypeException: Unknown gc type: 'Pause Young (Normal) (G1 Evacuation Pause)') on line number 4 (line="[1.015s][info][gc,start     ] GC(0) Pause Young (Normal) (G1 Evacuation Pause)")`
`WARNUNG [DataReaderUnifiedJvmLogging]: Didn't find parent event for partial event [1.026] GC(0) [Eden regions:: 24576K->0K(153600K), 0.0 secs] (line number 10, line="[1.026s][info][gc,heap      ] GC(0) Eden regions: 24->0(150)"`
`WARNUNG [DataReaderUnifiedJvmLogging]: Didn't find parent event for partial event [1.026] GC(0) [Survivor regions:: 0K->3072K(3072K), 0.0 secs] (line number 11, line="[1.026s][info][gc,heap      ] GC(0) Survivor regions: 0->3(3)"`
`WARNUNG [DataReaderUnifiedJvmLogging]: Didn't find parent event for partial event [1.027] GC(0) [Old regions:: 0K->4096K(0K), 0.0 secs] (line number 12, line="[1.027s][info][gc,heap      ] GC(0) Old regions: 0->4"`
`WARNUNG [DataReaderUnifiedJvmLogging]: Didn't find parent event for partial event [1.027] GC(0) [Humongous regions:: 5120K->5120K(0K), 0.0 secs] (line number 13, line="[1.027s][info][gc,heap      ] GC(0) Humongous regions: 5->5"`
`WARNUNG [DataReaderUnifiedJvmLogging]: Didn't find parent event for partial event [1.027] GC(0) [Metaspace:: 16948K->16948K(1064960K), 0.0 secs] (line number 14, line="[1.027s][info][gc,metaspace ] GC(0) Metaspace: 16948K->16948K(1064960K)"`

**Java 9/10 GC logging**
`[1.379s][info][gc,start     ] GC(0) Pause Young (G1 Evacuation Pause)`

**Java 11 GC logging**
`[1.015s][info][gc,start     ] GC(0) Pause Young (Normal) (G1 Evacuation Pause)`

There also seems to be different types than `Normal`. I found the following different warnings in my log file.
`WARNUNG [DataReaderUnifiedJvmLogging]: Failed to parse gc event (com.tagtraum.perf.gcviewer.imp.UnknownGcTypeException: Unknown gc type: 'Pause Young (Concurrent Start) (G1 Evacuation Pause)') on line number 401 (line="[25.574s][info][gc            ] GC(28) Pause Young (Concurrent Start) (G1 Evacuation Pause) 205M->131M(256M) 4.154ms")`
`WARNUNG [DataReaderUnifiedJvmLogging]: Failed to parse gc event (com.tagtraum.perf.gcviewer.imp.UnknownGcTypeException: Unknown gc type: 'Pause Young (Prepare Mixed) (G1 Evacuation Pause)') on line number 427 (line="[25.667s][info][gc,start      ] GC(30) Pause Young (Prepare Mixed) (G1 Evacuation Pause)")`

**GC logging configuration for all Java versions**
> -Xlog:gc*:file=gc.log

**Java 11 version**
> openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

**Comment by chewiebug** [comment]
Thank you very much for this hint! I will have to look into this.

Best regards,
Jörg

**Comment by Bohne** [comment]
I'm facing the same problem. Is there something like a workaround for this?

Thanks
Samuel

**Comment by chewiebug** [comment]
I have started working on this issue (see branch 
https://github.com/chewiebug/GCViewer/tree/feature/%23204/improve-parser-for-openjdk11). 
It looks a little better, but not quite ok.

**Comment by sudeepban** [comment]
@chewiebug is there any update on enabling GCViewer to parse Java 11 produced G1GC logs without errors?  I'm seeing the same errors reported in this issue using 1.36, and it seems to result in incomplete heap / pause detail in the report.

**Comment by chewiebug** [comment]
Hi @sudeepban

I have pushed a fix to the develop branch. The latest 1.36-SNAPSHOT
should handle JDK 11 G1 better.

Please let me know, if you still find parser warnings.

Best regards,
Jörg

**Comment by theobisproject** [comment]
Hi @chewiebug 

thanks for your work. I made another try and found some more warnings.
Please try this [gc.log](https://github.com/chewiebug/GCViewer/files/3282728/gc.log) file.

The unknown events are

- Pause Young (Concurrent Start) (Metadata GC Threshold)
- Pause Young (Normal) (GCLocker Initiated GC)

Also it complains about some partial events where no parent event could be found. I think this does not harm any of the statistics generated. But I personally would be interested to have this events in the event details and the diagram as they provide great insight what the gc has done.

**Comment by chewiebug** [comment]
Hi @theobisproject

Thank you for the sample log! I have improved the parser for gc event
names containing "()". Your sample now parses without warnings.

The partial events without parent events were followup errors of the
unknown events.

Are there still more parser warnings?

Best regards,
Jörg

**Comment by theobisproject** [comment]
I didn't find any other warnings in my tests. Looks good from my point of view 👍

**Comment by Bohne** [comment]
My warnings are also gone - thanks! Maybe its time for releasing GCViewer 1.36 ?! :-)

**Comment by krzyjab** [comment]
+1 for the new release :)

For those who are struggling with this as I did:
- build newest code from `develop` branch
- in case you're using custom GC logging options, you need to have level & tags enabled in the Unified JVM Logging for it to work, for example:
`-Xlog:gc*,safepoint,gc+heap=trace:file=gc.log:uptime,utctime,level,tags`

**Comment by chewiebug** [comment]
New release is done: [1.36](https://github.com/chewiebug/GCViewer/releases/tag/1.36).

Please open a new issue, if you find new issues with UnifiedLogging in Java 11.
