### ISSUE TITLE
Release 1.36 Please

### ISSUE THREAD

**Issue by kittylyst** [chewiebug/GCViewer#232]
Can you release 1.36 as a final version?

There have been quite a few fixes since 1.35 and it would be good to have a stable version number out there in Maven Central.

**Comment by chrisvest** [comment]
We are using 1.36-SNAPSHOT versions via 3rd party Maven repositories. We have not had any problems with GCViewer itself, but the use of 3rd party Maven repos is causing tooling problems and friction. Getting a final 1.36 release on Maven Central would be very helpful!

**Comment by jkwatson** [comment]
Would love to see this officially released!

**Comment by chewiebug** [comment]
Ok, I have heard you :-). Definitely time for a next release.

It might still take a few weeks, until I will have done the release,
because I have very little time for GCViewer at the moment.

Best regards,
Jörg

**Comment by kittylyst** [comment]
Thanks @chewiebug - is there anything that anyone else can do to help here? I have cycles that could be contributed if it would help make the release faster.

**Comment by chewiebug** [comment]
Hi Ben

Thank you very much for offering your help! I would like to do the final
step in automating the release to avoid delays next time. This should
not take really much of my time, but needs to fit in besides working and
my other hobbies. The gaps there are a bit narrow at the moment. That's
the main reason for me saying, that it might take a few weeks.

Best regards,
Jörg

**Comment by chewiebug** [comment]
Finally, the release is done. Automation is now much better, so the next release might not take as long as this one.
