### ISSUE TITLE
{"result":"{\"error\":515,\"message\":\"Unable to detect JVM version or GC type from the log file.\"}"}

### ISSUE THREAD

**Issue by GAURAVJAYSWAL** [chewiebug/GCViewer#233]
{"result":"{\"error\":515,\"message\":\"Unable to detect JVM version or GC type from the log file.\"}"}

**Comment by chewiebug** [comment]
Could you provide more information, please?

Are you really using GCViewer? The message you posted, is in JSON
format, which is nowhere used in GCViewer.

A sample log file is always very helpful!

Best regards,
Jörg

**Comment by chewiebug** [comment]
If you have more information, please reopen this issue.
