### ISSUE TITLE
The environment variable JAVA_HOME is not correctly set.

### ISSUE THREAD

**Issue by Jeffrey2971** [chewiebug/GCViewer#266]
The environment variable JAVA_HOME is not correctly set.

**Comment by chewiebug** [comment]
I am inclined to agree with you even without seeing any errormessage.

However, most probably, this is not an issue of the GCViewer repository, but with the setup of your own development environment.

What are you trying to do?

Best regards
Jörg 


-------- Original Message --------
From: "小扎飞、" ***@***.***>
Sent: 3 March 2023 06:16:30 CET
To: chewiebug/GCViewer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [chewiebug/GCViewer] The environment variable JAVA_HOME is not correctly set. (Issue #266)

The environment variable JAVA_HOME is not correctly set.


-- 
Reply to this email directly or view it on GitHub:
https://github.com/chewiebug/GCViewer/issues/266
